torch/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('users.urls', namespace='account')),
    url(r'', include('management.urls', namespace='management')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url

from .views import (
    IndexView,
    LoginView,
    RegisterView,
    ProfileView,
    LogoutView,
    UpdateProfileView,
)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^profile/', ProfileView.as_view(), name='profile'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^update-profile/', UpdateProfileView.as_view(), name='update_profile')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Torch</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/torch.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
</head>

<body class="blue-grey darken-4">
    {# NAVBAR #}
    <nav class="z-depth-1 white">
        <div class="container">
        <div class="nav-wrapper">
            <a href="{% url 'account:index' %}" class="brand-logo black-text">Torch</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a href="{% url 'account:profile' %}" class="black-text waves-effect waves-green">{{ user.get_full_name }}</a></li>
                <li><a href="{% url 'account:logout' %}" class="black-text waves-effect waves-green">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:login' %}" class="black-text waves-effect waves-green">Login</a></li>
                <li><a href="{% url 'account:register' %}" class="black-text waves-effect waves-green">Register</a></li>
                {% endif %}
            </ul>
        </div>
        </div>
    </nav>
    {# END NAVBAR #} {% block content %} {% endblock %} {% block sidebar %} {% endblock %}
    <script type="text/javascript" src="{% static 'js/torch.js' %}"></script>
</body>

</html>