torch/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('users.urls', namespace='account')),
    url(r'', include('management.urls', namespace='management')),
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url

from .views import (
    IndexView,
    LoginView,
    RegisterView,
    ProfileView,
    LogoutView,
    UpdateProfileView,
)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^profile/', ProfileView.as_view(), name='profile'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^update-profile/', UpdateProfileView.as_view(), name='update_profile')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    """ Create a custom class for the users or accounts to enable adding of
    custom fields """

    REGULAR = 'regular'
    STAFF = 'staff'

    LIST_OF_ROLES = (
        (REGULAR, 'Regular'),
        (STAFF, 'Staff'),
    )

    MALE = 'male'
    FEMALE = 'female'

    LIST_OF_GENDER = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    email = models.EmailField(unique=True)
    username = models.CharField(max_length=50, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True)
    middle_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)

    department = models.ForeignKey('management.Department', null=True)
    course = models.ForeignKey('management.Course', null=True)

    nick_name = models.CharField(max_length=20, null=True)
    birthdate = models.DateField(null=True)
    mobile_number = models.CharField(max_length=13, null=True)
    age = models.IntegerField(null=True)
    father_name = models.CharField(max_length=250, null=True)
    mother_maiden_name = models.CharField(max_length=250, null=True)
    address = models.CharField(max_length=250, null=True)

    affiliations = models.TextField(null=True)
    awards = models.TextField(null=True)

    role = models.CharField(max_length=7, choices=LIST_OF_ROLES, default=REGULAR)
    gender = models.CharField(max_length=6, choices=LIST_OF_GENDER, default=MALE)

    date_joined = models.DateTimeField()

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('first_name', 'last_name')

    objects = CustomUserManager()

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return '{}'.format(self.first_name)

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

# Steps
# 1. Import `AbstractBaseUser` which has the core implementation for a user model
# 2. Define your model fields. Add `get_short_name()` method.
# 3. Use `USERNAME_FIELD` to identify your unique field which will replace `username`
#    as the default unique field
# 4. Create a custom manager for a custom user model
# 5. Inherit `PermissionsMixin` for the permissions

users/forms.py
from django import forms

from .models import User

class RegisterForm(forms.ModelForm):
    """ Form for registration """

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password')
        widgets = {
            'password': forms.PasswordInput()
        }

    def save(self):
        User.objects.create_user(
            self.cleaned_data.get('email'),
            self.cleaned_data.get('first_name'),
            self.cleaned_data.get('last_name'),
            self.cleaned_data.get('password'),
        )


class LoginForm(forms.Form):
    """ Form for login """

    email = forms.EmailField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput())


class AccountForm(forms.ModelForm):
    """ Form for account """

    email = forms.EmailField(required=False)
    middle_name = forms.CharField(required=False)
    affiliations = forms.CharField(widget=forms.Textarea, required=False)
    awards = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'middle_name', 'last_name', 'nick_name',
            'department', 'course', 'birthdate', 'mobile_number', 'age', 'father_name',
            'mother_maiden_name', 'address', 'affiliations', 'awards',)

    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.fields['affiliations'].widget.attrs['class'] = 'materialize-textarea'
        self.fields['awards'].widget.attrs['class'] = 'materialize-textarea'

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .forms import RegisterForm, LoginForm, AccountForm
from .models import User

class IndexView(TemplateView):
    """ View for index
    """

    template_name = 'users/index.html'


class LoginView(TemplateView):
    """ View for login
    """

    template_name = 'users/login.html'

    def get_context_data(self):
        context = super(LoginView, self).get_context_data()
        context['form'] = LoginForm()
        return context

    def post(self, request):
        context_data = {}
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(request, username=request.POST.get('email'),
                password=request.POST.get('password'))
            if user:
                login(request, user)
                return redirect('account:profile')
            messages.warning(request, 'No account is associated with the credentials provided.')

        context_data['form'] = form
        return render(request, 'users/login.html', context_data)


class RegisterView(TemplateView):
    """ View for register """

    template_name = 'users/register.html'

    def get_context_data(self):
        context = super(RegisterView, self).get_context_data()
        form = RegisterForm()
        context['form'] = RegisterForm()
        return context

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        context_data = {}
        context_data['form'] = form
        return render(request, 'users/register.html', context_data)


class ProfileView(TemplateView):
    """ view for account """

    template_name = 'users/profile.html'

    def get_context_data(self):
        context = super(ProfileView, self).get_context_data()
        user = User.objects.get(pk=self.request.user.id)
        context['user'] = user
        return context


class UpdateProfileView(TemplateView):
    """ View for updating profile """

    template_name = 'users/update_profile.html'

    def get_context_data(self):
        context = super(UpdateProfileView, self).get_context_data()
        user = User.objects.get(pk=self.request.user.id)
        context['form'] = AccountForm(initial=user.__dict__)
        return context

    def post(self, request):
        context_data = {}
        form = AccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('account:profile')
        context_data['form'] = form
        return render(request, 'users/update_profile.html', context_data)


class LogoutView(View):
    """ View for logout """

    def get(self, request):
        logout(request)
        return redirect('account:index')

templates/users/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1 class="white-text">Welcome to Torch!</h1>
    </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="container">
    <br><br><br>
    <div class="row">
        <div class="col m4 offset-m4">
            <div class="card z-depth-3">
                <div class="card-content">
                    {% if messages %}
                        {% for message in messages %}
                        <script type="text/javascript">
                            Materialize.toast("{{ message }}", 10000, 'rounded amber black-text')
                        </script>
                        {% endfor %}
                    {% endif %}
                    <h5 class="center">Login to Torch</h5>
                    <form action="{% url 'account:login' %}" method="post">
                        {% csrf_token %} {% for field in form.visible_fields %}
                        <div class="input-field">
                            <label>{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-block green">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col m6 offset-m3">
            <div class="card">
                <div class="card-content">
                    <h5>Hi {{ user.get_short_name }}!</h5>
                    <p>First name: {{ user.first_name }}</p>
                    <p>Middle name: {{ user.middle_name }}</p>
                    <p>Last name: {{ user.last_name }}</p>
                    <p>Nick name: {{ user.nick_name }}</p>
                    <p>Department: {{ user.department }}</p>
                    <p>Course: {{ user.course }}</p>
                    <p>Birthdate: {{ user.birthdate }}</p>
                    <p>Mobile number: {{ user.mobile_number }}</p>
                    <p>Age: {{ user.age }}</p>
                    <p>Father's name: {{ user.father_name }}</p>
                    <p>Mother's maiden name: {{ user.mother_maiden_name }}</p>
                    <p>Address: {{ user.address }}</p>
                    <p>Affiliations: {{ user.affiliations }}</p>
                    <p>Awards: {{ user.awards }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="container">
    <br><br><br>
    <div class="row">
        <div class="col m4 offset-m4">
            <div class="card z-depth-3">
                <div class="card-content">
                    {% if messages %}
                        {% for message in messages %}
                        <script type="text/javascript">
                            Materialize.toast("{{ message }}", 10000, 'rounded amber black-text')
                        </script>
                        {% endfor %}
                    {% endif %}
                    <h5 class="center">Register to Torch</h5>
                    <form action="{% url 'account:register' %}" method="post">
                        {% csrf_token %} {% for field in form.visible_fields %}
                        <div class="input-field">
                            <label>{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-block green">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col m6 offset-m3">
            <div class="card">
                <div class="card-content">
                    <form action="{% url 'account:update_profile' %}" method="post">
                        {% csrf_token %} {% for field in form.visible_fields %}
                        <div class="input-field">
                            <label>{{ field.label }}</label>
                            {{ field | add_class:'form-control' }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-success btn-block green">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}